### ISSUE TITLE
Hi bro! From Nexus Mods :)

### ISSUE THREAD

**Issue by snookilow** [Gravechapa/popcnt_hotpatch_cyberpunk#2]
Please update to 1.06 thank you very much! You have the best mod!

**Comment by Gravechapa** [comment]
Well, I have updated it. But I don't have any hardware to test it. You can test it If you like. Please let me know if it works correctly.
[icudt.zip](https://github.com/Gravechapa/popcnt_hotpatch_cyberpunk/files/5759540/icudt.zip)

**Comment by snookilow** [comment]
I tested it in action on a q9505 processor - everything works great. Thank you!

**Comment by Gravechapa** [comment]
Thanks for testing.
