### ISSUE TITLE
sse4.2fix 

### ISSUE THREAD

**Issue by Nikitocpt** [Gravechapa/popcnt_hotpatch_cyberpunk#4]
how can i use it(((( heeeeellllpppp pleeeeese

**Comment by Gravechapa** [comment]
You can either use the precompiled binary from [here](https://www.nexusmods.com/cyberpunk2077/mods/353?tab=description) or build it yourself.

**Comment by Nikitocpt** [comment]
Thanks

вс, 31 янв. 2021 г., 07:36 Marchenko Ivan <notifications@github.com>:

**Comment by Denisamir** [comment]
Does this SSE 4.2 fix  works for Cyberpunk 2077 1.11 (steam version) ? Or it works with only GOG????

**Comment by Nikitocpt** [comment]
I dont yse the steam version, at the gog version it works pretty well


пн, 1 февр. 2021 г., 23:17 Denisamir <notifications@github.com>:

**Comment by Denisamir** [comment]
Никита, у меня наоборот нет GOG версии, а есть steam версия Cyberpunk. И что удивительно в интернете только фиксы SSE 4.2 для GOG версии.....  в базовой версии, на которую ты ссылаешься, написано что тестировалась на GOG-версии тоже. Есть ли смысл проверять на steam версии или можно нарваться на бан от steam?

**Comment by Gravechapa** [comment]
Фиксы для 1.04 и 1.05 я делал на основе бинарников из steam. Все остальные на основе gog-овских. Вроде они не отличаются, но это не точно. ~~Вы можете проверить совпадает ли md5 хэш у бинарников. Если они одинаковые, бинарники скорее всего идентичны. Чтобы сгенерировать хэш вы можете использовать команду в PowerShell:
`Get-FileHash -Path <путь до Cyberpunk2077.exe> -Algorithm MD5`
`v1.11 gog MD5: 12C966B56A78CFAA6B8F9652F6C9D239`~~
P.S. В стиме вас забанить не должны.

Edit: Неважно, они отличаются. Но похоже только цифровой подписью. Должно работать.

**Comment by Denisamir** [comment]
1.11 steam MD5 c61d931a6b4d2694f517a9db0c811fc7 *Cyberpunk2077.exe
естественно главный .exe файл будет отличаться от версии GOG.
удобнее считать хэш суммы через totalcommander
